app = "reklama-analytics-1"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "4000"
  CLIENT_DIR = "../client"
  DB_PATH = "/data/data.sqlite"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


